[package]
name = "kindle-highlight-deleter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fantoccini = "0.19.3"
tokio = { version = "1.34.0", features = ["full"] }
url = "2.4.1"
